import "./globals.css";
import css from "./layout.module.css";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={css.main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
