import "./globals.css";
import css from "./layout.module.css";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={css.header}>
          <nav className={css.nav}>
            <Link href="/" className={css.navLink}>
              Home
            </Link>
            <Link href="/characters" className={css.navLink}>
              Characters
            </Link>
            <Link href="/locations" className={css.navLink}>
              Locations
            </Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer>Foooter</footer>
      </body>
    </html>
  );
}
